### ISSUE TITLE
Duplicate hover contents

### ISSUE THREAD

**Issue by sqs** [sourcegraph/browser-extensions#175]
Repro:

1. "Use Sourcegraph extensions" = on
1. Go to https://github.com/theupdateframework/notary/blob/fb795b0bc868746ed2efa2cd7109346bc7ddf0a4/server/storage/rethinkdb.go
1. Hover over a token

The hover contents are duplicated, as though it's fetching them via the builtin LSP client and via the `langserver/*` extensions and merging them.

**Comment by sqs** [comment]
Yes, I removed it because it was broken (no Router context, needed for the Links). No extensions other than the langserver/go extension. I’ll dig into it more

**Comment by chrismwendt** [comment]
I saw this briefly while working on something else, but I don't have a consistent repro.

**Comment by chrismwendt** [comment]
I noticed that this bug only manifests while the options page is open. I suspect this is happening because https://github.com/sourcegraph/browser-extensions/blob/903acddcdd690339e491668852cbddb062c034c5/src/extension/scripts/background.tsx#L462 is being executed both in the background script and the options page (via a transitive `import`). That line it should only execute in the background script. To avoid this double execution, I'm looking into either splitting up the imports or conditionally executing that based on which script is running.

**Comment by chrismwendt** [comment]
Submitted a fix https://github.com/sourcegraph/browser-extensions/pull/182. The root cause was that I was transitively importing background.tsx from the options page, which caused multiple port listeners to be added, which caused duplicate messages to be sent to the content scripts.

I plan to completely prevent transitive imports of the entrypoints in another PR.
